# ALL PARAMETERS OF CODE SHOULD BE CONTROLLED FROM CONFIG

# paths of MIDOG++ dataset files
annot_path: data/slides/MIDOGpp.sqlite
image_dir: data/slides # original 40x slides

# labels
labels_dir: data/labels # directory path to save labels (as a csv per slide)

# parameters for resizing slides to a different magnification
resize: False # whether to resize slides
magn: 20 # magnifcation to rescale to
resized_dir: data/20x_slides # directory to store resized slides

# patching
patch_dir: data/patches # directory path to save directory
save_patch_ims: False
patch_ims_dir: data/patch_imgs # directory path to save images of patches (as .png)
patch_size: 64

# cellpose patching
save_cell_patch_ims: False
cell_dir: data/cells/patches
cell_masks_dir: data/cells/masks
cell_outlines_dir: data/cells/outlines
cell_patch_ims_dir: data/cells/imgs
cell_centers_dir: data/cells/centers
# patch size same as patching patch size
